//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_sql_entityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ajuste
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> priority { get; set; }
        public bool value { get; set; }
        public bool state { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<double> numerico { get; set; }
        public Nullable<int> last_active_by { get; set; }
        public Nullable<System.DateTime> last_active_at { get; set; }
    }
}
